config:
  prefix: "<gray>[</gray><green>Lobby</green><gray>]</gray>"
  send-welcome-message: true

  lobby:
    boost-cooldown: 5
    boost-strength: 2.2
    tp-cooldown: 3

    # The style of signs
    # Variables available: $size
    game-signs:
      line0: "<aqua>===============</aqua>"
      line1: "<gray>Join a game</gray>"
      line2: "<gold>$size</gold>"
      line3: "<aqua>===============</aqua>"

    visibility-db: "player-visibility.yml"

  queue:
    team-selection-item: "WHITE_BANNER"
    map-voting-item: "MAP"
    leave-item: "OAK_DOOR"